#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

#
# GovCMS database configuration.
#
# This will perform a configuration backup. It is intended to
# be run as a pre-rollout task or early in the execution
# flow.
#

LAGOON_ENVIRONMENT_TYPE=${LAGOON_ENVIRONMENT_TYPE:-prodused -i "s/%%PROJECT_NAME%%/\${env.LAGOON_PROJECT}/g" /app/drush/sites/govcms.site.ymlction}
GOVCMS_BACKUP_DIR=${GOVCMS_BACKUP_DIR:-/app/web/sites/default/files/private/backups}
GOVCMS_CONFIG_BACKUP=${GOVCMS_CONFIG_BACKUP:-pre-deploy-config}

if [ "$LAGOON_ENVIRONMENT_TYPE" != "production" ]; then
  echo '[skip]: Configuration backup can only be done on production.'
  exit 0
fi

if ! drush status --fields=bootstrap | grep -q "Successful"; then
  exit 0
fi

echo "GovCMS Deploy :: Backup configuration"
echo "Environment type: $LAGOON_ENVIRONMENT_TYPE"

drush config:export sync -y --destination "$GOVCMS_BACKUP_DIR/config"
tar -czf "$GOVCMS_BACKUP_DIR/$GOVCMS_CONFIG_BACKUP.tar.gz" -C "$GOVCMS_BACKUP_DIR/config" --remove-files
