#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

#
# GovCMS update database.
#

LAGOON_ENVIRONMENT_TYPE=${LAGOON_ENVIRONMENT_TYPE:-production}
GOVCMS_DEPLOY_UPDB=${GOVCMS_DEPLOY_UPDB:-true}
GOVCMS_DEPLOY_PRE_UPDB=${GOVCMS_DEPLOY_PRE_UPDB:-false}
GOVCMS_CACHE_REBUILD_PRE_UPDB=${GOVCMS_CACHE_REBUILD_PRE_UPDB:-false}

echo "GovCMS Deploy :: Update Database"

if [ "$GOVCMS_DEPLOY_UPDB" != "true" ]; then
  # Skip the database updates for this deploy.
  echo "[skip]: Environment variable is set to skip."
  exit 0
fi

if [ "$GOVCMS_DEPLOY_PRE_UPDB" != "false" ]; then
  # If we have the pre_updb task configured for this deployment
  # then we don't need to re-run the databases updates.
  echo "[skip]: Pre-deploy updates were applied."
  exit 0
fi

if ! drush status --fields=bootstrap | grep -q "Successful"; then
  echo '[skip]: Site is not available.'
  exit 0
fi

# Drupal 9 upgrade support.
# First time an environment updates from 8.x to 9.x
if drush status --format=json | grep drupal-version | grep -q "\"9"; then
  echo "[info]: Detected Drupal 9 codebase."
  if drush pm-list --core --format=json | grep -q "\"8"; then
    echo "[info]: Detected Drupal 8 core database schema."
    echo "[info]: Running cache-rebuild prior to database update."
    drush cr
  fi
fi

if [ "$GOVCMS_CACHE_REBUILD_PRE_UPDB" != "false" ]; then
  # Allow forced cache-rebuild prior to database updates.
  drush cr
fi

echo "[info]: Preparing database update."
drush updatedb -y

echo "[success]: Completed successfully."
