#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

#
# GovCMS database sync
#
# This will pull a database from the production
# environment.
#

LAGOON_ENVIRONMENT_TYPE=${LAGOON_ENVIRONMENT_TYPE:-production}
GOVCMS_DEPLOY_WORKFLOW_CONTENT=${GOVCMS_DEPLOY_WORKFLOW_CONTENT:-retain}

echo "GovCMS Deploy :: Database synchronisation"

if [ "$LAGOON_ENVIRONMENT_TYPE" = "production" ]; then
  echo "[skip]: Production environment can't be synced."
  exit 0
fi

echo "[info]: Check that the site can be bootstrapped"

# If the site is not valid drush returns a 130 status and grep -c produces
# inconcsistent return status causing the script to fail.
BOOTSTRAP=$(drush status --fields=bootstrap)

# Synchronise the environment on the first deploy.
if [ $? -eq 0 ] && [ "$GOVCMS_DEPLOY_WORKFLOW_CONTENT" != "import" ]; then
  echo "[skip]: Site can be bootstrapped and the workflow is not set to import."
  exit 0
fi

echo "Environment type: $LAGOON_ENVIRONMENT_TYPE"

# drush --alias-path=/etc/drush/sites sql-sync @ci.prod @self -y
drush --alias-path=/etc/drush/sites sql-sync @prod @self -y

echo "[success]: Completed successfully."
exit 0
# @TODO: sql-san?
