#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

#
# GovCMS database sync
#
# This will pull a database from the production
# environment.
#

LAGOON_ENVIRONMENT_TYPE=${LAGOON_ENVIRONMENT_TYPE:-production}
GOVCMS_DEPLOY_WORKFLOW_CONTENT=${GOVCMS_DEPLOY_WORKFLOW_CONTENT:-retain}

echo "GovCMS Deploy :: Database synchronisation"

if [ "$LAGOON_ENVIRONMENT_TYPE" = "production" ]; then
  echo "[skip]: Production environment can't be synced."
  exit 0
fi

echo "[info]: Check that the site can be bootstrapped"
BOOTSTRAP=$(drush status --fields=bootstrap)

# shellcheck disable=SC2181
if [ $? -ne 0 ] || [ "$(echo "$BOOTSTRAP" | grep -c "Successful")" -eq 0 ]; then
  # This will ensure that the databse is synchronised on the first deploy
  # of an enviornment in lagoon.
  echo "[info]: Site could not be bootstrapped... syncing."
  drush --alias-path=/etc/drush/sites sql-sync @govcms.prod @self -y
  exit 0
fi

if [ "$GOVCMS_DEPLOY_WORKFLOW_CONTENT" != "import" ]; then
  # Allow per environment overrides for the synchronisation flow, if the site
  # has bootstrapped but the environment is not set to "import" for the workflow
  # then we will not synchronise the database.
  echo "[skip]: Site can be bootstrapped and the workflow is not set to import."
  exit 0
fi

echo "[info]: Environment type: $LAGOON_ENVIRONMENT_TYPE"
echo "[info]: Preparing database sync"

# drush --alias-path=/etc/drush/sites sql-sync @ci.prod @self -y
drush --alias-path=/etc/drush/sites sql-sync @govcms.prod @self -y

echo "[success]: Completed successfully."
exit 0
# @TODO: sql-san?
