#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

#!/usr/bin/env bash
# Drutiny wrapper.

APP_DIR=${APP_DIR:-/app}

if [[ ! -d "$APP_DIR/audit-site" ]]; then
  cp -Rf /opt/audit-site "$APP_DIR"
  chmod 775 "$APP_DIR/audit-site/vendor/bin/drutiny"
fi

CUR_DIR=$(pwd)

cd "$APP_DIR/audit-site"
vendor/bin/drutiny "$@"

cd $CUR_DIR
