#!/usr/bin/env bash
# Drutiny wrapper.

APP_DIR=${APP_DIR:-/app}
DRUTINY_DIR=${DRUTINY_DIR:-$APP_DIR/sites/all/drutiny}

CUR_DIR=$(pwd)

cd $DRUTINY_DIR
${APP_DIR}/vendor/bin/drutiny "$@"
# @todo can this error handling be replaced with "set -euo pipefail"
result=$?

cd $CUR_DIR

exit $result
