#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

# Run phpunit in a typical GovCMS Drupal project.
# Pass in path to lint, eg ./vendor/bin/lint web/modules/custom.

# Allow path override.
APP_DIR=${APP_DIR:-$PWD}

echo "@todo get this working"
${APP_DIR}/vendor/bin/phpunit --bootstrap ${APP_DIR}/tests/phpunit/bootstrap.php --configuration  ${APP_DIR}/tests/phpunit/phpunit.xml "$@"
