#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail
# Code linting path pass in.

APP_DIR=${APP_DIR:-/app}

# Lint code.
touch ${APP_DIR}/"$@"/index.php # Avoid "no files found" error. @see https://github.com/JakubOnderka/PHP-Parallel-Lint/issues/108
${APP_DIR}/vendor/bin/parallel-lint --exclude /app/tests/vendor -e php,inc,module,theme,install,profile,test ${APP_DIR}/"$@"

# Check code standards.
${APP_DIR}/vendor/bin/phpcs --standard=${APP_DIR}/tests/phpcs.xml ${APP_DIR}/"$@"

# Check code mess.
${APP_DIR}/vendor/bin/phpmd ${APP_DIR}/"$@" text codesize,unusedcode,cleancode
