#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail
# PHPUnit testing.

APP_DIR=${APP_DIR:-/app}

${APP_DIR}/vendor/bin/phpunit --bootstrap ${APP_DIR}/tests/phpunit/bootstrap_phpunit.inc --configuration  ${APP_DIR}/tests/phpunit/phpunit.xml "$@"
