#!/usr/bin/env bash
set -euo pipefail

#
# GovCMS validate theme yaml files.
#
# Ensure files in the theme directory contain valid YAML.
#

GOVCMS_THEME_FILES=${GOVCMS_THEME_FILES:-}
GOVCMS_YAML_LINT=${GOVCMS_YAML_LINT:-}

echo "GovCMS Validate :: Yaml lint theme files"

if [ -z "${GOVCMS_THEME_FILES}" ]; then
  GOVCMS_THEME_FILES=$(find ./web/themes -type f -name "*.yml")
fi

if [ -z "${GOVCMS_YAML_LINT}" ]; then
  GOVCMS_YAML_LINT=govcms-yaml_lint
  if ! command -v "$GOVCMS_YAML_LINT" > /dev/null 2>&1; then
    GOVCMS_YAML_LINT=/app/vendor/bin/govcms-yaml_lint
  fi
fi

IFS_BAK="$IFS"
IFS=$'\n'

for file in $GOVCMS_THEME_FILES; do
  if ! $GOVCMS_YAML_LINT "$file"; then
    echo "[fail]: $file failed lint";
    exit 1;
  fi
done

IFS=$IFS_BAK
echo "[success]: No YAML issues in theme files."
