#!/usr/bin/env bash
set -euo pipefail

#
# GovCMS validate TFA config.
# Ensure that TFA is properly configured on a running site.
#

GOVCMS_PREPARE_XML_SCRIPT=${GOVCMS_PREPARE_XML_SCRIPT:-govcms-prepare-xml}
GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-validate-active-tfa}

# Drush 12 support.
DRUSH="${GOVCMS_DRUSH:-none}"
if [ "$DRUSH" == "none" ]; then
  DRUSH=$(which /app/vendor/bin/drush > /dev/null 2>&1 && echo "/app/vendor/bin/drush" || echo "/usr/local/bin/drush")
fi

FAILURES=""

echo "GovCMS Validate :: Validate TFA config on active site"

TFA_CONFIG=$("$DRUSH" config:get --include-overridden tfa.settings --format=json)

TFA_ENABLED=$(jq -r '.enabled' <<< "${TFA_CONFIG}")
if [[ "${TFA_ENABLED}" != 1 && "${TFA_ENABLED}" != 'true' ]]; then
  echo "[fail]: TFA not enabled"
  FAILURES="${FAILURES},${TFA_ENABLED}"
else
  echo "[info]: TFA is enabled"
fi

TFA_REQUIRED_ROLES=$(jq -r '.required_roles' <<< "${TFA_CONFIG}")
if [[ "${TFA_REQUIRED_ROLES}" == "[]" ]]; then
  echo "[fail]: TFA is not required for any role"
  FAILURES="${FAILURES},no_role_required}"
else
  TFA_AUTHENTICATED_REQUIRED=$(jq -r '.authenticated' <<< "${TFA_REQUIRED_ROLES}")
  if [[ "${TFA_AUTHENTICATED_REQUIRED}" != "authenticated" ]]; then
    echo "[fail]: TFA is not required for authenticated users"
    FAILURES="${FAILURES},${TFA_AUTHENTICATED_REQUIRED}"
  else
    echo "[info]: TFA is required for authenticated users"
  fi
fi

if [ -x "${GOVCMS_PREPARE_XML_SCRIPT}" ]; then
  ${GOVCMS_PREPARE_XML_SCRIPT} --failures="${FAILURES}" --total="tfa_enabled,tfa_authenticated_enabled" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.ValidateActiveTfa"
fi

if [ -z "${FAILURES}" ]; then
  echo "[success]: TFA is actively enabled and properly configured"
  exit 0
fi

echo "[fail]: TFA is not actively enabled or enabled but not properly configured"
exit 1
