#!/usr/bin/env bash
# shellcheck disable=SC2162,SC2046,SC2002,SC2034
set -euo pipefail

#
# GovCMS validate platform yaml.
#
# Ensures that the necessary Platform files contain
# valid yaml.
#

GOVCMS_PLATFORM_FILES=${GOVCMS_PLATFORM_FILES:-}
GOVCMS_YAML_LINT=${GOVCMS_YAML_LINT:-}
GOVCMS_PREPARE_XML_SCRIPT=${GOVCMS_PREPARE_XML_SCRIPT:-govcms-prepare-xml}
GOVCMS_OUTFILE=${GOVCMS_OUTFILE:-govcms-validate-platform}

FAILURES=""
function join_char { local IFS="$1" shift; echo "$*"; }

echo "GovCMS Validate :: Yaml lint platform files"

if [ -z "${GOVCMS_PLATFORM_FILES}" ]; then
  GOVCMS_PLATFORM_FILES=$(find . -type f \( -name '.lagoon.yml' -o -name 'docker-compose.yml' \))
fi

if [ -z "${GOVCMS_YAML_LINT}" ]; then
  GOVCMS_YAML_LINT=govcms-yaml_lint
  if ! command -v "$GOVCMS_YAML_LINT" > /dev/null 2>&1; then
    GOVCMS_YAML_LINT=/app/vendor/bin/govcms-yaml_lint
  fi
fi

IFS_BAK="$IFS"
IFS=$'\n'

for file in $GOVCMS_PLATFORM_FILES; do
  if ! $GOVCMS_YAML_LINT "$file"; then
    echo "[fail]: $file failed lint";
    FAILURES="$FAILURES,$file"
  fi
done

IFS=$IFS_BAK

if [ -x ${GOVCMS_PREPARE_XML_SCRIPT} ]; then
  FILE_LFS=$(join_char , "${GOVCMS_PLATFORM_FILES}")
  ${GOVCMS_PREPARE_XML_SCRIPT} --failures="${FAILURES}" --total="${FILE_LFS}" --name="${GOVCMS_OUTFILE}" --fail-message="GovCMS.QA.IllegalPermissions"
fi

if [ -z "${FAILURES}" ]; then
  echo "[success]: No YAML issues in platform files."
  exit 0
fi

echo "[fail]: YAML problems detected"
exit 1
