#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

SCAFFOLD="https://github.com/govCMS/govcms8-scaffold-paas.git"
WORKSPACE="/tmp/govcms8-scaffold-paas"

flavour=$(grep  "^type: " .version.yml | awk -F ": " '{print $2}')
if [ "$flavour" = "saas" ] || [ "$flavour" = "paas" ] || [ "$flavour" = "saasplus" ] ; then
    echo "GovCMS build flavour: $flavour"
else
    echo "Not a relevant SaaS/PaaS project."
    exit_code 0
fi

function compare() {
    if [ "$1" != "$2" ] ; then
        echo -e "\033[0;91mProblem\033[0m:" "$4"
        echo -e "  Current value:\n    --$1--"
        echo -e "  Expected value:\n    --$2--"
        return 1
    fi
    echo -e "\033[0;32mOK:\033[0m" "$3"
    return 0
}

# May add versioning, currently just cloning master.
rm -Rf "$WORKSPACE"
git clone --depth=1 --quiet "$SCAFFOLD" "$WORKSPACE"

if [ "$flavour" = "saas" ] ; then

    compare \
        "$(cat composer.json | jq -c '.repositories')" \
        "$(cat $WORKSPACE/composer.json | jq -c '.repositories')" \
        "Composer repositories are expected." \
        "The repositories section of your composer.json should match the scaffold."

    compare \
        "$(cat composer.json | jq -c '.extra["enable-patching"]')" \
        "$(cat $WORKSPACE/composer.json | jq -c '.extra["enable-patching"]')" \
        "Composer patching is enabled." \
        "Your composer.json must enable patching."

    compare \
        "$(cat composer.json | jq -c '.["minimum-stability"]')" \
        "$(cat $WORKSPACE/composer.json | jq -c '.["minimum-stability"]')" \
        "Minimum stablity is dev." \
        "Your composer.json must set minimum stability to dev."

    compare \
        " $(find web/modules/custom -type f -name "*.info.yml")" \
        " " \
        "No custom modules found." \
        "There should be no modules in web/sites/default/modules or web/modules"

fi

exit $exit_code
