#!/usr/bin/env bash
IFS=$'\n\t'
set -euo pipefail

GOVCMS_REPORT_MODE=${GOVCMS_REPORT_MODE:-1}

echo "[Deprecation]: GovCMS audit-site is deprecated and will be removed in scaffold-tooling@3.3.0"

if [[ GOVCMS_REPORT_MODE -ne 1 ]]; then
  echo '[fail]: Deprecated script used.'
  exit 1
fi
